name: YToxicHome
api:
- 3.0.0
- 4.0.0
version: '1.0.0_alpha'
load: POSTWORLD
main: yxmingy\ToxicHome\Main
author: xMingcommands:
  hs:
    description: "家园系统主指令"
    permission: yxmingy.hs.command
    usage: "/hs [obj]"
permissions:
  yxmingy.hs.command: 
    default: op
